<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'fullname'	=> 'Administrator',
                'username' => 'adminmuscab',
                'password'	=> bcrypt('adminMus4b123!*'),
                'role' => 'Admin',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // cabang
            [
                'fullname'	=> 'PCMPML001',
                'username' => 'PCMPML001',
                'password'	=> bcrypt('PCMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PCMPML002',
                'username' => 'PCMPML002',
                'password'	=> bcrypt('PCMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PCMPML003',
                'username' => 'PCMPML003',
                'password'	=> bcrypt('PCMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PCMPML004',
                'username' => 'PCMPML004',
                'password'	=> bcrypt('PCMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PCMPML005',
                'username' => 'PCMPML005',
                'password'	=> bcrypt('PCMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PCMPML006',
                'username' => 'PCMPML006',
                'password'	=> bcrypt('PCMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PCMPML007',
                'username' => 'PCMPML007',
                'password'	=> bcrypt('PCMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // pcu
            [
                'fullname'	=> 'PRMPCU001',
                'username' => 'PRMPCU001',
                'password'	=> bcrypt('PRMPCU123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU002',
                'username' => 'PRMPCU002',
                'password'	=> bcrypt('PRMPCU123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU003',
                'username' => 'PRMPCU003',
                'password'	=> bcrypt('PRMPCU123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU004',
                'username' => 'PRMPCU004',
                'password'	=> bcrypt('PRMPCU123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //pci
            [
                'fullname'	=> 'PRMPCI001',
                'username' => 'PRMPCI001',
                'password'	=> bcrypt('PRMPCI123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCI002',
                'username' => 'PRMPCI002',
                'password'	=> bcrypt('PRMPCI123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCI003',
                'username' => 'PRMPCI003',
                'password'	=> bcrypt('PRMPCI123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCI004',
                'username' => 'PRMPCI004',
                'password'	=> bcrypt('PRMPCI123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // pamtim
            [
                'fullname'	=> 'PRMPMT001',
                'username' => 'PRMPMT001',
                'password'	=> bcrypt('PRMPMT123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPMT002',
                'username' => 'PRMPMT002',
                'password'	=> bcrypt('PRMPMT123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPMT003',
                'username' => 'PRMPMT003',
                'password'	=> bcrypt('PRMPMT123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPMT004',
                'username' => 'PRMPMT004',
                'password'	=> bcrypt('PRMPMT123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // pambar
            [
                'fullname'	=> 'PRMPMB001',
                'username' => 'PRMPMB001',
                'password'	=> bcrypt('PRMPMB123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],    
            [
                'fullname'	=> 'PRMPMB002',
                'username' => 'PRMPMB002',
                'password'	=> bcrypt('PRMPMB123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],    
            [
                'fullname'	=> 'PRMPMB003',
                'username' => 'PRMPMB003',
                'password'	=> bcrypt('PRMPMB123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],    
            [
                'fullname'	=> 'PRMPMB004',
                'username' => 'PRMPMB004',
                'password'	=> bcrypt('PRMPMB123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PONTIR
            [
                'fullname'	=> 'PRMPTR001',
                'username' => 'PRMPTR001',
                'password'	=> bcrypt('PRMPTR123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPTR002',
                'username' => 'PRMPTR002',
                'password'	=> bcrypt('PRMPTR123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPTR003',
                'username' => 'PRMPTR003',
                'password'	=> bcrypt('PRMPTR123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPTR004',
                'username' => 'PRMPTR004',
                'password'	=> bcrypt('PRMPTR123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PONDBED
            [
                'fullname'	=> 'PRMPDB001',
                'username' => 'PRMPDB001',
                'password'	=> bcrypt('PRMPDB123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPDB002',
                'username' => 'PRMPDB002',
                'password'	=> bcrypt('PRMPDB123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPDB003',
                'username' => 'PRMPDB003',
                'password'	=> bcrypt('PRMPDB123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPDB004',
                'username' => 'PRMPDB004',
                'password'	=> bcrypt('PRMPDB123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // BAMBU APUS
            [
                'fullname'	=> 'PRMBMA001',
                'username' => 'PRMBMA001',
                'password'	=> bcrypt('PRMBMA123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMBMA002',
                'username' => 'PRMBMA002',
                'password'	=> bcrypt('PRMBMA123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMBMA003',
                'username' => 'PRMBMA003',
                'password'	=> bcrypt('PRMBMA123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMBMA004',
                'username' => 'PRMBMA004',
                'password'	=> bcrypt('PRMBMA123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PARAKAN
            [
                'fullname'	=> 'PRMPRK001',
                'username' => 'PRMPRK001',
                'password'	=> bcrypt('PRMPRK123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPRK002',
                'username' => 'PRMPRK002',
                'password'	=> bcrypt('PRMPRK123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPRK003',
                'username' => 'PRMPRK003',
                'password'	=> bcrypt('PRMPRK123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPRK004',
                'username' => 'PRMPRK004',
                'password'	=> bcrypt('PRMPRK123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //aisyiyah
            [
                'fullname'	=> 'PCAPML001',
                'username' => 'PCAPML001',
                'password'	=> bcrypt('PCAPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PCAPML002',
                'username' => 'PCAPML002',
                'password'	=> bcrypt('PCAPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            //NA
            [
                'fullname'	=> 'PCNAPML001',
                'username' => 'PCNAPML001',
                'password'	=> bcrypt('PCNAPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PCNAPML002',
                'username' => 'PCNAPML002',
                'password'	=> bcrypt('PCNAPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            //pemuda muh
            [
                'fullname'	=> 'PCPMPML001',
                'username' => 'PCPMPML001',
                'password'	=> bcrypt('PCPMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PCPMPML002',
                'username' => 'PCPMPML002',
                'password'	=> bcrypt('PCPMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            
            // TAPAK SUCI
            [
                'fullname'	=> 'TSPML001',
                'username' => 'TSPML001',
                'password'	=> bcrypt('TSPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'TSPML002',
                'username' => 'TSPML002',
                'password'	=> bcrypt('TSPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // IPM
            [
                'fullname'	=> 'IPMPML001',
                'username' => 'IPMPML001',
                'password'	=> bcrypt('IPMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'IPMPML002',
                'username' => 'IPMPML002',
                'password'	=> bcrypt('IPMPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            
             // HW
             [
                'fullname'	=> 'HWPML001',
                'username' => 'HWPML001',
                'password'	=> bcrypt('HWPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'HWPML002',
                'username' => 'HWPML002',
                'password'	=> bcrypt('HWPML123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], 
    ]);
    }
}
